import { Poppins, Roboto } from "next/font/google";
import "../globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Header from "@/components/layouts/Header";
import Navbar from "@/components/layouts/Navbar";

const poppins = Poppins({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] });

const roboto = Roboto({ subsets: ["latin"], weight: ['100', '300', '400', '500', '700', '900'] });


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${poppins.className} ${roboto.className}`}>
                <Header />
                <Navbar showHide={false} />
                {children}</body>
        </html>
    );
}
